#Bütün Siparişleri Getir
GET http://localhost:3001/foods HTTP/1.1
Content-Type: application/json

###

#Sipariş Oluştur
POST http://localhost:3001/foods HTTP/1.1
Content-Type: application/json

{ "title": "Salata" }

###

#Siparişi Güncelle
PUT http://localhost:3001/foods/4721 HTTP/1.1
Content-Type: application/json

{ "title": "Pizza" }

###

#Siparişi Sil
DELETE http://localhost:3001/foods/51bc HTTP/1.1
Content-Type: application/json
